name: Build HavenJH Display

on:
  push:
    branches: [master]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.19.5'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release 

      - name: Create ZIP
        run: |
          cd build
          zip -r ../havenjh-web.zip web

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
         tag_name: latest
         name: Latest HavenJH Build
         files: havenjh-web.zip
